In [2]:
import pandas as pd
data = {'name': ['Alice','Bob','Charlie'],'age': [25,30,35]}
df= pd.DataFrame(data)
df

      name  age
0    Alice   25
1      Bob   30
2  Charlie   35

In [3]:
df.shape

(3, 2)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   age     3 non-null      int64
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes

In [5]:
df.describe()

        age
count   3.0
mean   30.0
std     5.0
min    25.0
25%    27.5
50%    30.0
75%    32.5
max    35.0

In [6]:
df['name']

0      Alice
1        Bob
2    Charlie
Name: name, dtype: object

In [7]:
df[['name','age']]

      name  age
0    Alice   25
1      Bob   30
2  Charlie   35

In [8]:
df[df['age']>28]

      name  age
1      Bob   30
2  Charlie   35

In [11]:
df['is_senior']=df['age']>28
df

      name  age  is_senior
0    Alice   25      False
1      Bob   30       True
2  Charlie   35       True

In [12]:
df.groupby('is_senior')['age'].mean()

is_senior
False    25.0
True     32.5
Name: age, dtype: float64